# ============================================================
# STREAMLIT APP
# PNEUMONIA DETECTION SYSTEM FROM X-RAY IMAGES
# ============================================================
#
# WORKFLOW:
#
# 1. Upload image
# 2. Check whether image is grayscale
#       ├── Color      -> REJECT
#       └── Grayscale  -> Continue
#
# 3. Detect modality
#       ├── X-ray -> Continue to pneumonia detection
#       ├── CT    -> STOP
#       └── MRI   -> STOP
#
# 4. X-ray pneumonia detection
#       ├── Normal
#       └── Pneumonia
#
# 5. Generate PDF report
#
# ============================================================


# ============================================================
# IMPORTS
# ============================================================

import os
import io
from datetime import datetime

import numpy as np
import streamlit as st
import tensorflow as tf

from PIL import Image

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as ReportLabImage
)


# ============================================================
# STREAMLIT CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Pneumonia Detection System",
    page_icon="🩻",
    layout="centered",
    initial_sidebar_state="expanded"
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    .main-title {
        text-align: center;
        font-size: 32px;
        font-weight: 700;
        margin-bottom: 8px;
    }

    .subtitle {
        text-align: center;
        font-size: 16px;
        margin-bottom: 25px;
    }

    .section-title {
        font-size: 22px;
        font-weight: 600;
        margin-top: 20px;
    }

    .result-box {
        padding: 20px;
        border-radius: 12px;
        border: 1px solid #cccccc;
        margin-top: 15px;
        margin-bottom: 15px;
    }

    .normal-box {
        background-color: #eaf7ea;
    }

    .pneumonia-box {
        background-color: #fdeaea;
    }

    .modality-box {
        background-color: #eef4ff;
    }

    .rejected-box {
        background-color: #fff1f1;
    }

    .stopped-box {
        background-color: #fff8e6;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# TITLE
# ============================================================

st.markdown(
    '<div class="main-title">'
    'Pneumonia Detection System from X-ray Images'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'Medical Image Modality Verification and Pneumonia Detection'
    '</div>',
    unsafe_allow_html=True
)


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.abspath(__file__)
)


# ============================================================
# MODEL PATHS
# ============================================================

MODALITY_MODEL_PATH = os.path.join(
    BASE_DIR,
    "modality_classifier.keras"
)

PNEUMONIA_MODEL_PATH = os.path.join(
    BASE_DIR,
    "best_xception_pneumonia_model.keras"
)


# ============================================================
# MODALITY CLASS MAPPING
# ============================================================
#
# Generated by the Kaggle modality training code:
#
# 0_X-ray -> 0
# 1_CT    -> 1
# 2_MRI   -> 2
#
# ============================================================

MODALITY_LABELS = {
    0:  "X-ray",
    1:  "MRI",
    2:  "CT"
}


# ============================================================
# PNEUMONIA CLASS MAPPING
# ============================================================
#
# Expected:
#
# NORMAL    -> 0
# PNEUMONIA -> 1
#
# ============================================================

PNEUMONIA_LABELS = {
    0: "Normal",
    1: "Pneumonia"
}


# ============================================================
# LOAD MODALITY MODEL
# ============================================================

@st.cache_resource
def load_modality_model():

    if not os.path.isfile(
        MODALITY_MODEL_PATH
    ):

        raise FileNotFoundError(
            f"""
Modality model was not found.

Expected:
{MODALITY_MODEL_PATH}

Required file:
modality_classifier.keras
"""
        )

    model = tf.keras.models.load_model(
        MODALITY_MODEL_PATH,
        compile=False
    )

    return model


# ============================================================
# LOAD PNEUMONIA MODEL
# ============================================================

@st.cache_resource
def load_pneumonia_model():

    if not os.path.isfile(
        PNEUMONIA_MODEL_PATH
    ):

        raise FileNotFoundError(
            f"""
Pneumonia model was not found.

Expected:
{PNEUMONIA_MODEL_PATH}

Required file:
best_xception_pneumonia_model.keras
"""
        )

    model = tf.keras.models.load_model(
        PNEUMONIA_MODEL_PATH,
        compile=False
    )

    return model


# ============================================================
# GET MODEL INPUT SIZE
# ============================================================

def get_model_input_size(model):

    try:

        input_shape = model.input_shape

        if isinstance(
            input_shape,
            list
        ):

            input_shape = input_shape[0]

        height = input_shape[1]
        width = input_shape[2]

        if (
            height is not None
            and width is not None
        ):

            return (
                int(height),
                int(width)
            )

    except Exception:
        pass

    return (
        224,
        224
    )


# ============================================================
# CHECK GRAYSCALE
# ============================================================

def is_grayscale_image(image):

    # --------------------------------------------------------
    # Native grayscale formats
    # --------------------------------------------------------

    if image.mode in [
        "1",
        "L",
        "I",
        "F",
        "I;16"
    ]:

        return True

    # --------------------------------------------------------
    # Convert to RGB for pixel comparison
    # --------------------------------------------------------

    rgb_image = image.convert(
        "RGB"
    )

    image_array = np.asarray(
        rgb_image
    )

    if (
        image_array.ndim != 3
        or image_array.shape[-1] != 3
    ):

        return True

    red = image_array[:, :, 0]
    green = image_array[:, :, 1]
    blue = image_array[:, :, 2]

    return (
        np.array_equal(
            red,
            green
        )
        and
        np.array_equal(
            green,
            blue
        )
    )


# ============================================================
# PREPROCESS IMAGE
# ============================================================

def preprocess_image(
    image,
    target_size
):

    # --------------------------------------------------------
    # Convert to grayscale
    # --------------------------------------------------------

    grayscale = image.convert(
        "L"
    )

    # --------------------------------------------------------
    # Resize
    # --------------------------------------------------------

    grayscale = grayscale.resize(
        target_size,
        Image.Resampling.BILINEAR
    )

    # --------------------------------------------------------
    # NumPy
    # --------------------------------------------------------

    image_array = np.asarray(
        grayscale
    ).astype(
        np.float32
    )

    # --------------------------------------------------------
    # Normalize
    # --------------------------------------------------------

    image_array = (
        image_array / 255.0
    )

    # --------------------------------------------------------
    # Grayscale → RGB
    #
    # Your models use:
    # (224, 224, 3)
    #
    # --------------------------------------------------------

    image_array = np.stack(
        [
            image_array,
            image_array,
            image_array
        ],
        axis=-1
    )

    # --------------------------------------------------------
    # Batch dimension
    # --------------------------------------------------------

    image_array = np.expand_dims(
        image_array,
        axis=0
    )

    return image_array


# ============================================================
# MODALITY PREDICTION
# ============================================================

def predict_modality(
    model,
    image
):

    target_size = get_model_input_size(
        model
    )

    processed_image = preprocess_image(
        image,
        target_size
    )

    prediction = model.predict(
        processed_image,
        verbose=0
    )

    prediction = np.asarray(
        prediction
    ).reshape(-1)

    # --------------------------------------------------------
    # Require exactly 3 classes
    # --------------------------------------------------------

    if len(prediction) != 3:

        raise ValueError(
            f"""
Invalid modality model output.

Expected 3 classes:
X-ray
CT
MRI

Received:
{len(prediction)}
"""
        )

    # --------------------------------------------------------
    # Ensure probabilities
    # --------------------------------------------------------

    if (
        np.any(prediction < 0)
        or
        np.any(prediction > 1)
        or
        not np.isclose(
            np.sum(prediction),
            1.0,
            atol=1e-3
        )
    ):

        prediction = tf.nn.softmax(
            prediction
        ).numpy()

    # --------------------------------------------------------
    # Predicted class
    # --------------------------------------------------------

    class_index = int(
        np.argmax(prediction)
    )

    confidence = float(
        prediction[class_index]
    )

    modality = MODALITY_LABELS.get(
        class_index,
        "Unknown"
    )

    return (
        modality,
        confidence,
        prediction
    )


# ============================================================
# PNEUMONIA PREDICTION
# ============================================================

def predict_pneumonia(
    model,
    image
):

    target_size = get_model_input_size(
        model
    )

    processed_image = preprocess_image(
        image,
        target_size
    )

    prediction = model.predict(
        processed_image,
        verbose=0
    )

    prediction = np.asarray(
        prediction
    ).reshape(-1)

    # ========================================================
    # TWO CLASS SOFTMAX
    # ========================================================

    if len(prediction) == 2:

        if (
            np.any(prediction < 0)
            or
            np.any(prediction > 1)
            or
            not np.isclose(
                np.sum(prediction),
                1.0,
                atol=1e-3
            )
        ):

            prediction = tf.nn.softmax(
                prediction
            ).numpy()

        class_index = int(
            np.argmax(prediction)
        )

        confidence = float(
            prediction[class_index]
        )

        diagnosis = PNEUMONIA_LABELS[
            class_index
        ]

        return (
            diagnosis,
            confidence,
            prediction
        )

    # ========================================================
    # SINGLE SIGMOID
    # ========================================================

    if len(prediction) == 1:

        probability = float(
            prediction[0]
        )

        if (
            probability < 0
            or
            probability > 1
        ):

            probability = float(
                tf.sigmoid(
                    prediction[0]
                ).numpy()
            )

        if probability >= 0.5:

            diagnosis = "Pneumonia"

            confidence = probability

        else:

            diagnosis = "Normal"

            confidence = (
                1.0 - probability
            )

        return (
            diagnosis,
            confidence,
            probability
        )

    # ========================================================
    # INVALID MODEL
    # ========================================================

    raise ValueError(
        f"""
Invalid pneumonia model output.

Expected:
2-class softmax
OR
1-class sigmoid

Received:
{len(prediction)} outputs
"""
    )


# ============================================================
# CREATE PDF REPORT
# ============================================================

def create_pdf_report(
    image,
    modality,
    modality_confidence,
    diagnosis=None,
    diagnosis_confidence=None
):

    pdf_buffer = io.BytesIO()

    document = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=18,
        leading=22,
        spaceAfter=8
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=10,
        leading=14,
        spaceAfter=15
    )

    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=13,
        leading=16,
        spaceBefore=10,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        "ReportNormal",
        parent=styles["Normal"],
        fontSize=10,
        leading=14
    )

    result_style = ParagraphStyle(
        "ReportResult",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=16,
        leading=20,
        spaceAfter=10
    )

    story = []

    # ========================================================
    # TITLE
    # ========================================================

    story.append(
        Paragraph(
            "Pneumonia Detection System from X-ray Images",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Medical Image Analysis Report",
            subtitle_style
        )
    )

    # ========================================================
    # DATE
    # ========================================================

    report_date = datetime.now().strftime(
        "%d %B %Y, %I:%M:%S %p"
    )

    # ========================================================
    # INFORMATION TABLE
    # ========================================================

    story.append(
        Paragraph(
            "Analysis Information",
            heading_style
        )
    )

    report_data = [
        [
            "Analysis Date",
            report_date
        ],
        [
            "Image Type",
            "Grayscale"
        ],
        [
            "Detected Modality",
            modality
        ],
        [
            "Modality Confidence",
            f"{modality_confidence * 100:.2f}%"
        ]
    ]

    # --------------------------------------------------------
    # Add pneumonia result only for X-ray
    # --------------------------------------------------------

    if diagnosis is not None:

        report_data.append(
            [
                "Final Result",
                diagnosis
            ]
        )

        report_data.append(
            [
                "Diagnosis Confidence",
                f"{diagnosis_confidence * 100:.2f}%"
            ]
        )

    report_table = Table(
        report_data,
        colWidths=[
            55 * mm,
            105 * mm
        ]
    )

    report_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    9
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                )
            ]
        )
    )

    story.append(
        report_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================================
    # IMAGE
    # ========================================================

    story.append(
        Paragraph(
            "Analyzed Image",
            heading_style
        )
    )

    image_buffer = io.BytesIO()

    image.convert(
        "RGB"
    ).save(
        image_buffer,
        format="JPEG"
    )

    image_buffer.seek(0)

    report_image = ReportLabImage(
        image_buffer,
        width=100 * mm,
        height=100 * mm
    )

    story.append(
        report_image
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================================
    # FINAL RESULT
    # ========================================================

    if diagnosis is not None:

        story.append(
            Paragraph(
                "Final Pneumonia Analysis",
                heading_style
            )
        )

        story.append(
            Paragraph(
                f"<b>{diagnosis}</b>",
                result_style
            )
        )

        story.append(
            Paragraph(
                f"Model confidence: "
                f"{diagnosis_confidence * 100:.2f}%",
                ParagraphStyle(
                    "Confidence",
                    parent=normal_style,
                    alignment=TA_CENTER,
                    spaceAfter=15
                )
            )
        )

    else:

        story.append(
            Paragraph(
                f"The uploaded image was identified as "
                f"<b>{modality}</b>. Pneumonia detection was "
                f"not performed because the pneumonia model "
                f"is intended only for chest X-ray images.",
                normal_style
            )
        )

    # ========================================================
    # DISCLAIMER
    # ========================================================

    story.append(
        Spacer(1, 15)
    )

    story.append(
        Paragraph(
            "<b>Research Disclaimer:</b> This application is "
            "intended for research and decision-support purposes. "
            "The result should not be considered a medical diagnosis "
            "and should be reviewed by a qualified healthcare "
            "professional.",
            normal_style
        )
    )

    document.build(
        story
    )

    pdf_buffer.seek(0)

    return pdf_buffer.getvalue()


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "System Information"
    )

    st.markdown(
        """
        ### Processing Pipeline

        **Step 1**
        Image upload

        **Step 2**
        Grayscale verification

        **Step 3**
        X-ray / CT / MRI classification

        **Step 4**
        X-ray → Pneumonia / Normal

        **Step 5**
        PDF report
        """
    )

    st.divider()

    st.subheader(
        "Required Models"
    )

    st.code(
        """
modality_classifier.keras

best_xception_pneumonia_model.keras
        """,
        language="text"
    )


# ============================================================
# FILE UPLOADER
# ============================================================

uploaded_file = st.file_uploader(
    "Upload Medical Image",
    type=[
        "png",
        "jpg",
        "jpeg",
        "bmp",
        "tif",
        "tiff"
    ],
    help=(
        "Upload a grayscale medical image. "
        "Color images will be rejected."
    )
)


# ============================================================
# MAIN PROCESSING
# ============================================================

if uploaded_file is not None:

    # ========================================================
    # READ IMAGE
    # ========================================================

    try:

        image = Image.open(
            uploaded_file
        )

        image.load()

    except Exception as error:

        st.error(
            "Unable to read the uploaded image."
        )

        st.code(
            str(error)
        )

        st.stop()

    # ========================================================
    # DISPLAY IMAGE
    # ========================================================

    st.markdown(
        '<div class="section-title">'
        'Uploaded Image'
        '</div>',
        unsafe_allow_html=True
    )

    st.image(
        image,
        caption="Uploaded medical image",
        width="stretch"
    )

    # ========================================================
    # IMAGE INFORMATION
    # ========================================================

    col1, col2 = st.columns(2)

    with col1:

        st.write(
            f"**Image mode:** `{image.mode}`"
        )

    with col2:

        st.write(
            f"**Resolution:** "
            f"`{image.width} × {image.height}`"
        )

    st.divider()

    # ========================================================
    # ANALYZE BUTTON
    # ========================================================

    analyze = st.button(
        "Analyze",
        type="primary",
        width="stretch"
    )

    # ========================================================
    # ANALYSIS START
    # ========================================================

    if analyze:

        # ====================================================
        # STEP 1
        # GRAYSCALE CHECK
        # ====================================================

        if not is_grayscale_image(
            image
        ):

            st.markdown(
                '<div class="result-box rejected-box">',
                unsafe_allow_html=True
            )

            st.error(
                "Image Rejected"
            )

            st.write(
                "The uploaded image is a color image."
            )

            st.write(
                "Only grayscale medical images are accepted."
            )

            st.markdown(
                "</div>",
                unsafe_allow_html=True
            )

            st.stop()

        # ====================================================
        # GRAYSCALE ACCEPTED
        # ====================================================

        st.success(
            "Grayscale image detected."
        )

        # ====================================================
        # STEP 2
        # LOAD MODALITY CLASSIFIER
        # ====================================================

        with st.spinner(
            "Loading modality classifier..."
        ):

            try:

                modality_model = (
                    load_modality_model()
                )

            except Exception as error:

                st.error(
                    "Modality classifier could not be loaded."
                )

                st.code(
                    str(error)
                )

                st.stop()

        # ====================================================
        # STEP 3
        # MODALITY DETECTION
        # ====================================================

        with st.spinner(
            "Identifying X-ray, CT, or MRI..."
        ):

            try:

                (
                    modality,
                    modality_confidence,
                    modality_probabilities
                ) = predict_modality(
                    modality_model,
                    image
                )

            except Exception as error:

                st.error(
                    "Modality detection failed."
                )

                st.code(
                    str(error)
                )

                st.stop()

        # ====================================================
        # DISPLAY MODALITY
        # ====================================================

        st.markdown(
            '<div class="result-box modality-box">',
            unsafe_allow_html=True
        )

        st.subheader(
            "Detected Image Type"
        )

        st.write(
            f"## {modality}"
        )

        st.write(
            f"Confidence: "
            f"**{modality_confidence * 100:.2f}%**"
        )

        st.markdown(
            "</div>",
            unsafe_allow_html=True
        )

        # ====================================================
        # MODALITY PROBABILITIES
        # ====================================================

        with st.expander(
            "View modality probabilities"
        ):

            st.write(
                f"X-ray: "
                f"{modality_probabilities[0] * 100:.2f}%"
            )

            st.progress(
                float(
                    modality_probabilities[0]
                )
            )

            st.write(
                f"CT: "
                f"{modality_probabilities[1] * 100:.2f}%"
            )

            st.progress(
                float(
                    modality_probabilities[1]
                )
            )

            st.write(
                f"MRI: "
                f"{modality_probabilities[2] * 100:.2f}%"
            )

            st.progress(
                float(
                    modality_probabilities[2]
                )
            )

        # ====================================================
        # IMPORTANT CONTROL LOGIC
        #
        # ONLY X-RAY CONTINUES.
        #
        # CT AND MRI STOP HERE.
        # ====================================================

        if modality != "X-ray":

            # ------------------------------------------------
            # CT OR MRI
            # ------------------------------------------------

            st.markdown(
                '<div class="result-box stopped-box">',
                unsafe_allow_html=True
            )

            st.warning(
                f"{modality} image detected."
            )

            st.write(
                "Pneumonia detection has been stopped."
            )

            st.write(
                "The pneumonia model is used only "
                "for X-ray images."
            )

            st.markdown(
                "</div>",
                unsafe_allow_html=True
            )

            # ------------------------------------------------
            # IMPORTANT:
            #
            # There is NO pneumonia model call here.
            #
            # This stops the workflow after modality
            # detection.
            # ------------------------------------------------

            st.stop()

        # ====================================================
        # ONLY X-RAY REACHES THIS POINT
        # ====================================================

        st.success(
            "X-ray image verified. "
            "Proceeding to pneumonia detection."
        )

        # ====================================================
        # LOAD PNEUMONIA MODEL
        # ====================================================

        with st.spinner(
            "Loading proposed pneumonia model..."
        ):

            try:

                pneumonia_model = (
                    load_pneumonia_model()
                )

            except Exception as error:

                st.error(
                    "Pneumonia model could not be loaded."
                )

                st.code(
                    str(error)
                )

                st.stop()

        # ====================================================
        # PNEUMONIA DETECTION
        # ====================================================

        with st.spinner(
            "Analyzing X-ray for Pneumonia or Normal..."
        ):

            try:

                (
                    diagnosis,
                    diagnosis_confidence,
                    pneumonia_probabilities
                ) = predict_pneumonia(
                    pneumonia_model,
                    image
                )

            except Exception as error:

                st.error(
                    "Pneumonia detection failed."
                )

                st.code(
                    str(error)
                )

                st.stop()

        # ====================================================
        # FINAL RESULT
        # ====================================================

        if diagnosis == "Pneumonia":

            st.markdown(
                '<div class="result-box pneumonia-box">',
                unsafe_allow_html=True
            )

            st.error(
                "Pneumonia Detected"
            )

            st.write(
                f"Confidence: "
                f"**{diagnosis_confidence * 100:.2f}%**"
            )

            st.markdown(
                "</div>",
                unsafe_allow_html=True
            )

        else:

            st.markdown(
                '<div class="result-box normal-box">',
                unsafe_allow_html=True
            )

            st.success(
                "Normal"
            )

            st.write(
                f"Confidence: "
                f"**{diagnosis_confidence * 100:.2f}%**"
            )

            st.markdown(
                "</div>",
                unsafe_allow_html=True
            )

        # ====================================================
        # PNEUMONIA PROBABILITIES
        # ====================================================

        if (
            isinstance(
                pneumonia_probabilities,
                np.ndarray
            )
            and
            pneumonia_probabilities.size == 2
        ):

            with st.expander(
                "View pneumonia probabilities"
            ):

                st.write(
                    f"Normal: "
                    f"{pneumonia_probabilities[0] * 100:.2f}%"
                )

                st.progress(
                    float(
                        pneumonia_probabilities[0]
                    )
                )

                st.write(
                    f"Pneumonia: "
                    f"{pneumonia_probabilities[1] * 100:.2f}%"
                )

                st.progress(
                    float(
                        pneumonia_probabilities[1]
                    )
                )

        # ====================================================
        # GENERATE PDF
        # ====================================================

        pdf_bytes = create_pdf_report(
            image=image,
            modality=modality,
            modality_confidence=modality_confidence,
            diagnosis=diagnosis,
            diagnosis_confidence=diagnosis_confidence
        )

        # ====================================================
        # DOWNLOAD REPORT
        # ====================================================

        st.divider()

        st.subheader(
            "Final Report"
        )

        st.download_button(
            "Download Final Report (PDF)",
            data=pdf_bytes,
            file_name="pneumonia_detection_report.pdf",
            mime="application/pdf",
            width="stretch"
        )
